### PR TITLE
Adjust InitMonsterGFX

### LINKED ISSUE #20: InitMonsterGFX: Same eax register is reused instead of ecx
This happens when calculating

```cpp
	Monsters[monst].MData = &monsterdata[mtype];
	Monsters[monst].flags_1 = monsterdata[mtype].flags;
	Monsters[monst].flags_2 = (monsterdata[mtype].flags - 64) >> 1;
	Monsters[monst].mMinHP = monsterdata[mtype].mMinHP;
	Monsters[monst].mMaxHP = monsterdata[mtype].mMaxHP;
	Monsters[monst].has_special = monsterdata[mtype].has_special;
	Monsters[monst].mAFNum = monsterdata[mtype].mAFNum;
```

Tried a few things (local variable, accessing `flags_1`), but nope:

image

### PR DESCRIPTION
**Pull request by AJenbo**
Fixes #20 Solution was in the beta :)

### CODE REVIEW

**Comment by seritools** [comment]
Woop 🎉

**Comment by mewmew** [comment]
> Fixes #20 Solution was in the beta :)

So great we have so many versions to check! Has anyone started to take a deeper look at the Mac version?

**Comment by mewmew** [comment]
> tool I was using failed to convert that to C code (seg-faulted)

Out of curiosity, what tool did you use?

**Comment by AJenbo** [comment]
https://retdec.com/ unfortunately it dosn't support the https://en.wikipedia.org/wiki/Preferred_Executable_Format and so you have to manually enter the entry point. If you figure out the correct values I would think you can get a some what usable output.

There are some resources on the format here: https://github.com/radare/radare2/issues/5079
And even a Go package if you feel like making a tool to read out the header: https://godoc.org/github.com/decomp/exp/bin/pef

The 1.09 can easily be extracted from the update download from Blizzard http://ftp.blizzard.com/pub/diablo/patches/mac/Diablo%201.09%20Update.hqx

**Pull request merged**
