### PR TITLE
Cleaned up `CalcPlrItemVals`

### PR DESCRIPTION
**Pull request by seritools**
So this is a pretty big function, which is why I added the decompilation outputs (both decompiled with capstone-rs with the same offset, so that relative jumps decode the same).

The remaining differences:

- The stack variable ordering isn't 100% correct (but very close!), but I'm guessing without other optimizer flags (the assume-no-aliasing flags seem to change that ordering a little bit, for example) it's impossible to get 100% right
- Some micro-optimizations are a bit different (I'm guessing alignment or global optimization stuff):
  - `xor eax, eax; inc eax` is sometimes generated as `push 1; pop eax` and similar tiny codegen differences. In some cases these
  -     ptrplr->_pStrength = sadd + ptrplr->_pBaseStr;
	    if ( ptrplr->_pStrength <= 0 )
	    {
		    ptrplr->_pStrength = 0;
	    }
    This one optimizes better in devilution for some reason. The orginal binary does everything in the `_pStrength` memory location, store `_pBaseStr`, add `sadd`, then check, then store `0` if `<= 0`. The new binary loads both `_pBaseStr` and `sadd` into registers, performs the addition and comparion in there, and just stores into `_pStrength` once...
  - I've seen these small changed flip around a lot since I started working on devilution, so I'm guessing some minimal changes can fix these and everything sort of snaps into place then. :)

[original asm](https://github.com/diasurgical/devil-nightly/files/2310828/orig.txt)
[devilution asm](https://github.com/diasurgical/devil-nightly/files/2310827/compare.txt)
(Try removing the offsets from the beginning of the lines to get a better look at the actual instruction differences)

I also added a `plr_class` enum after talking with @galaxyhaxz, since it's clear that there had to be another enum for the player class, because `_ui_classes` is, as its name tells us, obviously only for use in UI code (class selection I think?) Is the naming ok like that?

### CODE REVIEW

**Comment by galaxyhaxz** [comment]
Actually when looking at the raw decompiled code, it appears to be that way for all of them. It's possible `myplr` only references to the player being compared, but either way it should use `v5` instead of `v11`.
```
	plr[v5]._pStrength = v53 + plr[v5]._pBaseStr;
	v11 = myplr;
	v12 = &plr[myplr]._pStrength;
	if ( *v12 <= 0 )
		*v12 = 0;
	plr[v5]._pMagic = v60 + plr[v5]._pBaseMag;
	if ( plr[v11]._pMagic <= 0 )
		plr[v11]._pMagic = 0;
	plr[v5]._pDexterity = v52 + plr[v5]._pBaseDex;
	if ( plr[v11]._pDexterity <= 0 )
		plr[v11]._pDexterity = 0;
	v13 = &plr[v11]._pVitality;
	plr[v5]._pVitality = v61 + plr[v5]._pBaseVit;
	if ( *v13 <= 0 )
		*v13 = 0;
```

**Comment by seritools** [comment]
You're absolutely right... reverted that to the original cleanup code again. At least the stack is still fixed, however the function size is off again (seems to be missing some optimizations),

**Comment by seritools** [comment]
Alright, @galaxyhaxz reviewed the changes one more time and it looks good to him!

**Comment by seritools** [comment]
Now binary exact after the new compiler version helped fix a tiny cleanup bug (https://github.com/diasurgical/devil-nightly/commit/22718733d0a706953baddd0283b9a61a1fe3b852)

**Pull request merged**
