### PR TITLE
Clean up InitPlayerLoc

### PR DESCRIPTION
**Pull request by AJenbo**
Bin exact, but not supper happy with how the dpiece_defs_map_1 array pointers are handled. Any suggestions?

### CODE REVIEW

**Comment by nomdenom** [comment]
We should probably make a macro for that

**Comment by seritools** [comment]
Just cleaned up the code to be a lot more readable. I'm guessing the compiler just completely mangled up `gendung_get_dpiece_num_from_coord`, or it was hand optimized or something?

**Comment by squidcc** [comment]
gendung_get_dpiece_num_from_coord looks like it was hand-rolled to somehow rotate the co-ords. I'm not sure exactly what the transformation is; it's either something really obvious that I can't see or it's genius. Either way it seems like that function is always used to get the first index in dpiece_defs_map_1 which is why I suggested combining [MAXDUNX*MAXDUNX].

**Comment by nomdenom** [comment]
`dpiece_defs_map_2` was definitely a `[112][112][16]` array which you can see if you eg. look at the disassembly of the beta for `gendung_418D91`:
```
.text:00411C8B 040                 mov     eax, [ebp+var_20]
.text:00411C8E 040                 shl     eax, 5
.text:00411C91 040                 mov     ecx, [ebp+var_1C]
.text:00411C94 040                 mov     edx, ecx
.text:00411C96 040                 shl     ecx, 3
.text:00411C99 040                 sub     ecx, edx
.text:00411C9B 040                 shl     ecx, 9
.text:00411C9E 040                 add     eax, ecx
.text:00411CA0 040                 add     eax, offset dpiece_defs_map_2
.text:00411CA5 040                 mov     [ebp+var_30], eax
```
(note that the array offset calculation is a single block with no temporaries even in the unoptimized beta)
 
ref:
https://github.com/nomdenom/devil-beta/blob/1f9f575738c43b70771f7cf2e610bc94256a88ff/Source/gendung.cpp#L102-L108

**Comment by squidcc** [comment]
Can you do the same plot with different colors for each axis? Just to get a bit of a clearer idea of how it's mapped.

**Comment by nomdenom** [comment]
That's pretty.... trippy.
The first plot is how the function maps `(x,y) -> new_x` (note the corner with all 0) and the second one is `(x,y) -> new_y`
image

**Comment by AJenbo** [comment]
@nomdenom what did you use to generate the graphs? I feel like generating more data visualization is an area where I could defiantly improve my developer skills.

**Comment by squidcc** [comment]
I just wrote a C test programto see the results of different colored axes:
gendung00

Image on the left is the identity, next to it on the right is where each pixel ends up after remapping it using gendung_get_dpiece_num_from_coord.
I think the gist of it might be that it starts reading from the top left corner in a diagonal pattern (from lower left towards top right) towards the bottom right. Looking at the wikipedia page for [Triangular numbers](https://en.wikipedia.org/wiki/Triangular_number) confirms it, matching the formulas.

**Comment by seritools** [comment]
Merging this now since this function doesn't depend on the specific ordering for the dpiece_defs_maps.

**Pull request merged**
