### PR TITLE
Remove "A" suffix from all string-related win32 API function names

### PR DESCRIPTION
**Pull request by squidcc**
In reference to this: https://github.com/diasurgical/devil-nightly/commit/46f428dac58d039a3e541f55e81d7c0790ec022e#r30517142

I went through and fixed all the names of string-related win32 functions to their regular names since that's how they're normally referenced in source code. If there's evidence to the contrary feel free to reject this.

(Should be cosmetic changes only.)

### CODE REVIEW

**Comment by galaxyhaxz** [comment]
imports

**Comment by sskras** [comment]
@squidcc:
> The W/A names are normally not explicitly used (especially back when nobody cared about unicode).

Except for times when the binary uses a mix of both A/W variants, eg. Winetest units.  

There was some discussion ~10 years ago in Wine-devel between me and a list old-timer contributor.  Then they said "prove that it's worth before adding exact suffix".  I gave some example where suffixless function was actually asking for wide/unicode string then but the HQ were not persuaded by it.

Several years later they decided to switch to explicit style by their own.  For me, when living in the API chaos world (such as the WinAPI creates) means that I would better know for sure what kind of string is passed to a function on the first sight (so I don't have to do a guesswork).

But I guess you're probably right about D1 not using Unicode strings at all.  I just still haven't checked the loadable data resources directly (in a hex viewer:)

**Comment by squidcc** [comment]
The resources aren't going to help determine anything because the function names are redefined at compile time by the headers. As I said, our build still explicitly links to the *A symbols with this change because of that.

Normally the only argument for using non-explicit A/W names is if you are going to be compiling different builds with/without unicode support, and then you have to use the TCHAR variant stdlib functions too. Personally I don't like it because it makes intellisense next to useless - hovering over a function name just pops up the name it will be redefined to instead of showing the function definition. But here we're going for authenticity and I'm pretty sure this is how things would have been.

**Comment by sskras** [comment]
@squidcc,
> The resources aren't going to help determine anything because the function names are redefined at compile time by the headers.

... my idea was that if I cannot trust (or understand) the source then reading input string in function runtime helps to know its encoding and be sure about the exact fn variant.  Which luckily isn't the case here:)

So I just shared my general experience regarding A/W notation. (BTW, I don't like TCHAR too)

> But it doesn't mean that's how they were referenced in the source

Is there a chance that searching through all the assert strings would get us at some WinAPI fns of A/W kind?  Just a thought.

**Comment by galaxyhaxz** [comment]
> the windows headers add W or A to the names depending if UNICODE is defined

Makes sense, I was not aware of that. Diablo 2 also uses the 'A' everywhere.

**Comment by seritools** [comment]
The DX SDK code doesn't use A/W either, so removing the suffixes should be fine :)

**Pull request merged**
