### PR TITLE
Build using gold tools

### PR DESCRIPTION
**Pull request by AJenbo**
This fixes https://github.com/diasurgical/devil-nightly/issues/4

### CODE REVIEW

**Comment by seritools** [comment]
Hey, very cool to see this developing!

Currently travis errors with the `services` element not being supported on mac. Could you change it so that the docker build runs only for the linux targets for now?

Additionally, would you be up to publishing/creating the Dockerfile in a way that it grabs the needed files from the full VC folders when creating the image? We could create a devilution/riivaaja repo for that :)

That way, people can easily create their own images, for different VC versions for example.

**Comment by AJenbo** [comment]
I have written Travis support to see if it is possible to have services be conditional to platforms. My other idea would be to simply disable Mac build and do a LLVM build on Linux.

Yeah I would be happy to upload the Dockerfile to a repo. Yeah I was thinking about the idea of playing with different tags for different versions of VC, allowing us to quickly test different combinations as we progress with the bin accuracy. The one that we believe the most in at any given time could simply get a "gold" tag and if we find a better combination it would propagate to all other developers that use the image.

**Comment by seritools** [comment]
Very cool @AJenbo ! 👍 
I've created a repo for the docker/build files under the diasurgical org as well: https://github.com/diasurgical/riivaaja

Could you add a PR over there with the Dockerfile and a small readme with infos on how to get started over there? :)

@galaxyhaxz Since wine-based compile using the original tools works now in travis, what do you think? :)

**Comment by AJenbo** [comment]
Thanks it was an interesting thing to stitch together :)

PR added: https://github.com/diasurgical/riivaaja/pull/1

Thanks for all the support in this.

**Comment by mewmew** [comment]
Great work @AJenbo!

**Comment by ttdonovan** [comment]
Also should the "Build Status" badges in the `README.md` be updated?

**Comment by AJenbo** [comment]
I think it's there to show the main project status and if we changed it it would overwrite the main one at next merge. In any case general CI issues would be a different matter to this issue (VC6 specific)

**Comment by seritools** [comment]
Alright, looks like everything's working fine now and cleaned up nicely. Good work @AJenbo!

@ttdonovan Good idea, I've just added an additional badge for devil-nightly.

**Comment by AJenbo** [comment]
Thanks. I like the two rows of badges, that a good solution :+1:

**Pull request merged**
