### PR TITLE
Cleaned up `CheckInvSwap` and `CheckInvCut`

### PR DESCRIPTION
**Pull request by seritools**
Now binary exact except for the usual `xor; inc` vs `push 1; pop` switch...
Length went from 0xC2 to 0xA9 (like the original size)

Updated the type of `ItemStruct::_iIdentified` to `BOOL` as well (since every write to it actually is 0 or 1).

`bLoc` seems to be closely related to the `InvBody` slots, but don't match exactly - `bLoc = 4` means `InvBody[5]` and vice versa. Anyone got more info on this? :)

### CODE REVIEW

**Comment by mewmew** [comment]
> bLoc seems to be closely related to the InvBody slots, but don't match exactly - bLoc = 4 means InvBody[5] and vice versa. Anyone got more info on this? :)

Some random info :) It's not from the PSX, just reversing notes.

For the item player slots; including body, belt and inventory.

```c
enum {
	ITEM_PLAYER_NUM_BODY_0 =  0,
	ITEM_PLAYER_NUM_BODY_1 =  1,
	ITEM_PLAYER_NUM_BODY_2 =  2,
	ITEM_PLAYER_NUM_BODY_3 =  3,
	ITEM_PLAYER_NUM_BODY_4 =  4,
	ITEM_PLAYER_NUM_BODY_5 =  5,
	ITEM_PLAYER_NUM_BODY_6 =  6,
	ITEM_PLAYER_NUM_INV_0  =  7,
	ITEM_PLAYER_NUM_INV_1  =  8,
	ITEM_PLAYER_NUM_INV_2  =  9,
	ITEM_PLAYER_NUM_INV_3  = 10,
	ITEM_PLAYER_NUM_INV_4  = 11,
	ITEM_PLAYER_NUM_INV_5  = 12,
	ITEM_PLAYER_NUM_INV_6  = 13,
	ITEM_PLAYER_NUM_INV_7  = 14,
	ITEM_PLAYER_NUM_INV_8  = 15,
	ITEM_PLAYER_NUM_INV_9  = 16,
	ITEM_PLAYER_NUM_INV_10 = 17,
	ITEM_PLAYER_NUM_INV_11 = 18,
	ITEM_PLAYER_NUM_INV_12 = 19,
	ITEM_PLAYER_NUM_INV_13 = 20,
	ITEM_PLAYER_NUM_INV_14 = 21,
	ITEM_PLAYER_NUM_INV_15 = 22,
	ITEM_PLAYER_NUM_INV_16 = 23,
	ITEM_PLAYER_NUM_INV_17 = 24,
	ITEM_PLAYER_NUM_INV_18 = 25,
	ITEM_PLAYER_NUM_INV_19 = 26,
	ITEM_PLAYER_NUM_INV_20 = 27,
	ITEM_PLAYER_NUM_INV_21 = 28,
	ITEM_PLAYER_NUM_INV_22 = 29,
	ITEM_PLAYER_NUM_INV_23 = 30,
	ITEM_PLAYER_NUM_INV_24 = 31,
	ITEM_PLAYER_NUM_INV_25 = 32,
	ITEM_PLAYER_NUM_INV_26 = 33,
	ITEM_PLAYER_NUM_INV_27 = 34,
	ITEM_PLAYER_NUM_INV_28 = 35,
	ITEM_PLAYER_NUM_INV_29 = 36,
	ITEM_PLAYER_NUM_INV_30 = 37,
	ITEM_PLAYER_NUM_INV_31 = 38,
	ITEM_PLAYER_NUM_INV_32 = 39,
	ITEM_PLAYER_NUM_INV_33 = 40,
	ITEM_PLAYER_NUM_INV_34 = 41,
	ITEM_PLAYER_NUM_INV_35 = 42,
	ITEM_PLAYER_NUM_INV_36 = 43,
	ITEM_PLAYER_NUM_INV_37 = 44,
	ITEM_PLAYER_NUM_INV_38 = 45,
	ITEM_PLAYER_NUM_INV_39 = 46,
	ITEM_PLAYER_NUM_BELT_0 = 47,
	ITEM_PLAYER_NUM_BELT_1 = 48,
	ITEM_PLAYER_NUM_BELT_2 = 49,
	ITEM_PLAYER_NUM_BELT_3 = 50,
	ITEM_PLAYER_NUM_BELT_4 = 51,
	ITEM_PLAYER_NUM_BELT_5 = 52,
	ITEM_PLAYER_NUM_BELT_6 = 53,
	ITEM_PLAYER_NUM_BELT_7 = 54,
};
```

For the item body slots:

```c
enum {
	ITEM_BODY_HEAD       = 0,
	ITEM_BODY_RING_LEFT  = 1,
	ITEM_BODY_RING_RIGHT = 2,
	ITEM_BODY_AMULET     = 3,
	ITEM_BODY_HAND_LEFT  = 4,
	ITEM_BODY_HAND_RIGHT = 5,
	ITEM_BODY_CHEST      = 6,
};
```

For each individual 32x32 pixel slot.
ref: https://github.com/sanctuary/graphics/blob/master/inventory.png
ref: https://github.com/sanctuary/graphics/raw/master/inventory.xcf

```c
enum {
	INV_X_Y_SLOT_BODY_0_1 =  0,
	INV_X_Y_SLOT_BODY_0_2 =  1,
	INV_X_Y_SLOT_BODY_0_3 =  2,
	INV_X_Y_SLOT_BODY_0_4 =  3,
	INV_X_Y_SLOT_BODY_1   =  4,
	INV_X_Y_SLOT_BODY_2   =  5,
	INV_X_Y_SLOT_BODY_3   =  6,
	INV_X_Y_SLOT_BODY_4_1 =  7,
	INV_X_Y_SLOT_BODY_4_2 =  8,
	INV_X_Y_SLOT_BODY_4_3 =  9,
	INV_X_Y_SLOT_BODY_4_4 = 10,
	INV_X_Y_SLOT_BODY_4_5 = 11,
	INV_X_Y_SLOT_BODY_4_6 = 12,
	INV_X_Y_SLOT_BODY_5_1 = 13,
	INV_X_Y_SLOT_BODY_5_2 = 14,
	INV_X_Y_SLOT_BODY_5_3 = 15,
	INV_X_Y_SLOT_BODY_5_4 = 16,
	INV_X_Y_SLOT_BODY_5_5 = 17,
	INV_X_Y_SLOT_BODY_5_6 = 18,
	INV_X_Y_SLOT_BODY_6_1 = 19,
	INV_X_Y_SLOT_BODY_6_2 = 20,
	INV_X_Y_SLOT_BODY_6_3 = 21,
	INV_X_Y_SLOT_BODY_6_4 = 22,
	INV_X_Y_SLOT_BODY_6_5 = 23,
	INV_X_Y_SLOT_BODY_6_6 = 24,
	INV_X_Y_SLOT_INV_0    = 25,
	INV_X_Y_SLOT_INV_1    = 26,
	INV_X_Y_SLOT_INV_2    = 27,
	INV_X_Y_SLOT_INV_3    = 28,
	INV_X_Y_SLOT_INV_4    = 29,
	INV_X_Y_SLOT_INV_5    = 30,
	INV_X_Y_SLOT_INV_6    = 31,
	INV_X_Y_SLOT_INV_7    = 32,
	INV_X_Y_SLOT_INV_8    = 33,
	INV_X_Y_SLOT_INV_9    = 34,
	INV_X_Y_SLOT_INV_10   = 35,
	INV_X_Y_SLOT_INV_11   = 36,
	INV_X_Y_SLOT_INV_12   = 37,
	INV_X_Y_SLOT_INV_13   = 38,
	INV_X_Y_SLOT_INV_14   = 39,
	INV_X_Y_SLOT_INV_15   = 40,
	INV_X_Y_SLOT_INV_16   = 41,
	INV_X_Y_SLOT_INV_17   = 42,
	INV_X_Y_SLOT_INV_18   = 43,
	INV_X_Y_SLOT_INV_19   = 44,
	INV_X_Y_SLOT_INV_20   = 45,
	INV_X_Y_SLOT_INV_21   = 46,
	INV_X_Y_SLOT_INV_22   = 47,
	INV_X_Y_SLOT_INV_23   = 48,
	INV_X_Y_SLOT_INV_24   = 49,
	INV_X_Y_SLOT_INV_25   = 50,
	INV_X_Y_SLOT_INV_26   = 51,
	INV_X_Y_SLOT_INV_27   = 52,
	INV_X_Y_SLOT_INV_28   = 53,
	INV_X_Y_SLOT_INV_29   = 54,
	INV_X_Y_SLOT_INV_30   = 55,
	INV_X_Y_SLOT_INV_31   = 56,
	INV_X_Y_SLOT_INV_32   = 57,
	INV_X_Y_SLOT_INV_33   = 58,
	INV_X_Y_SLOT_INV_34   = 59,
	INV_X_Y_SLOT_INV_35   = 60,
	INV_X_Y_SLOT_INV_36   = 61,
	INV_X_Y_SLOT_INV_37   = 62,
	INV_X_Y_SLOT_INV_38   = 63,
	INV_X_Y_SLOT_INV_39   = 64,
	INV_X_Y_SLOT_BELT_0   = 65,
	INV_X_Y_SLOT_BELT_1   = 66,
	INV_X_Y_SLOT_BELT_2   = 67,
	INV_X_Y_SLOT_BELT_3   = 68,
	INV_X_Y_SLOT_BELT_4   = 69,
	INV_X_Y_SLOT_BELT_5   = 70,
	INV_X_Y_SLOT_BELT_6   = 71,
	INV_X_Y_SLOT_BELT_7   = 72,
};
```

```c
// assertion string from sync.c:
appfat_assertion_failed(186, "C:\\Diablo\\Direct\\sync.cpp", "(DWORD) sgnSyncPInv < NUM_INVLOC");
```

**Comment by seritools** [comment]
Thanks for the enums, will definitely work them in (especially in `CheckInvCut` I'll need the last two heavily ^^).

Found out what `bLoc` is/means, it was just too easy....
bLoc is bodyLoc (your 2nd enum)
And 4 and 5 are swapped in `CheckInvSwap` because thats what that function *should* do lol

**Comment by mewmew** [comment]
> Pretty close to the original binary except for the first loop, which generates differently. (TODO comment added) There are also some questionable double address calculations, which hopfully clear up when the loop is fixed as well.

That's great. I noticed the #15 issue you created to track this, basically an extension of https://github.com/diasurgical/devilution/issues/111

> Also added enums inv_body_loc and inv_xy_slot to clean up a lot of magic numbers in both functions, thanks @mewmew and @galaxyhaxz for the support :)

Glad that it helped a bit :)

Did you notice the `NUM_INVLOC = 7` enum at the end btw (from the debug release)? I think that can be used to infer what the enum of item body *should* have looked like. e.g. `INVLOC_HEAD`, etc.

**Comment by seritools** [comment]
> Did you notice the NUM_INVLOC = 7 enum at the end btw (from the debug release)? I think that can be used to infer what the enum of item body should have looked like. e.g. INVLOC_HEAD, etc.

Yup, that's where that additional enum member came from :) Sadly, you can't use enum members as array sizes in your struct definitions in the old compiler... (Complains about not being a constant expression)

**Comment by seritools** [comment]
Now binary exact with the new compiler version and the fixed loop (https://github.com/diasurgical/devil-nightly/commit/91b6568ef978f4f6a44b0258e99f9d5cac0e0b2a) 🎉

**Pull request merged**
