### PR TITLE
Clean up GetPlrGFXSize

### PR DESCRIPTION
**Pull request by AJenbo**
There is still something about how i'm initializing the two inner loops that is causing some comparisons and jump that i don't ket:
billede

### CODE REVIEW

**Comment by squidcc** [comment]
The loops have to evaluate their termination condition before first iteration. The initial values of a and w are known so the compiler emits fixed offsets.

**Comment by AJenbo** [comment]
1 and 11 was just me debugging, computer died before I could correct it last night. Should be 0 both

**Comment by AJenbo** [comment]
It's now bin exact, but i'm not really happy with the do-while loops that i ended up using.

**Comment by squidcc** [comment]
Did you try making those arrays const instead?

**Comment by AJenbo** [comment]
I had a brain fart and changed them to static instead of const. Now that I did it correctly it worked, thanks :)

**Comment by AJenbo** [comment]
Added InitPlrGFXMem here since it depends on GetPlrGFXSize being cleaned up, both are now bin exact

**Comment by seritools** [comment]
@squidcc yeah, there are `/* rdata */` comments in there, and for some reason these three are even above that comment. Double-checked and yup, those are in the rdata segment

**Comment by squidcc** [comment]
Hardly anything in the entire project is marked const, I thought that was intentional to make it build - no need to figure out what parameters are const if nothing is.

It would probably help a lot if things were correctly marked though.

**Comment by seritools** [comment]
Yup, will be done eventually. :)

**Comment by seritools** [comment]
@squidcc Investigated further and have seen a lot of codegen changes due to const vs non-const.

Talked to @galaxyhaxz who will go ahead and add const to all rdata stuff of the original binary. :)

**Pull request merged**
