### PR TITLE
Clean SetAutomapView

### PR DESCRIPTION
**Pull request by squidcc**
Reformats SetAutomapView into something readable. The switch/case structure seems to match the original code but that's about all - can't even coax the compiler to not set up a stack frame.

### CODE REVIEW

**Comment by seritools** [comment]
image

This is currently not even close to be binary accurate :(

**Comment by seritools** [comment]
> I didn't say it was, simply that it was cleaned up - at least you can tell it's a switch/case statement and that it's only writing to a single 2D array instead of random other variables.

And I definitely appreciate that! However currently, the only measurement on how correct the code is, is the binary exactness. With all the cases, stack usages, differently encoded conditional jumps etc I'm just not confident to merge this as-is.

**Comment by mewmew** [comment]
> And I definitely appreciate that! However currently, the only measurement on how correct the code is, is the binary exactness. With all the cases, stack usages, differently encoded conditional jumps etc I'm just not confident to merge this as-is.

Basically it's a two step approach. First get binary exactness, as that way we can be certain to have recreated the original. Step two is two create enough test cases to ensure that we don't break things, when later refactoring, cleaning up and rewriting to make it more modern and modular. Note, there will always exist a *binary perfect* version that will be called Devilution. Then there will be mods, rewrites, refactored versions, ported to different platforms and even programming languages (e.g. Rust, Go, Python). But all of that is step two. We are currently at step zero and a half. We are at step one when https://github.com/diasurgical/devil-nightly/milestone/1 is done.

**Comment by squidcc** [comment]
Right, but the problem with this particular file is that it's full of magic numbers and other things that aren't documented anywhere - some of the globals aren't even named and I'm pretty sure the ones that are aren't accurate. This is meant to be a starting point to figuring it out, rather than dumping a huge diff of the whole file.

**Comment by mewmew** [comment]
> Right, but the problem with this particular file is that it's full of magic numbers and other things that aren't documented anywhere - some of the globals aren't even named and I'm pretty sure the ones that are aren't accurate. This is meant to be a starting point to figuring it out, rather than dumping a huge diff of the whole file.

Definitely good to have for documentation purposes and to increase understanding!

**Comment by AJenbo** [comment]
galaxyhaxz isn't currently working on clean up so I woudn't look at his code for how to do that.

@squidcc at the moment we are still working on figuring out what the style should be like exactly, most of that work can be followed here https://github.com/diasurgical/devilution/issues/182
As such we aren't strict on the style either, but it should at least be some what consistent. Parts like this makes the code hard to read:
```
		if (solid) {
			if (GetAutomapType(x+1, y, FALSE)==0x4007)
				automapview[x+1][y] = 1;
		} else if (GetAutomapType(x, y-1, FALSE)&0x4000)
			automapview[x][y-1] = 1;
```
Instead I think going for something like the following would be acceptable:
```
		if (solid) {
			if ( GetAutomapType(x+1, y, FALSE) == 0x4007 ) {
				automapview[x+1][y] = 1;
			}
		} else if ( GetAutomapType(x, y-1, FALSE) & 0x4000 ) {
			automapview[x][y-1] = 1;
		}
```

**Comment by squidcc** [comment]
What about consistency of spaces after/before brackets?
My point is if you're going to enforce style guidelines they need to be complete, otherwise code will need to be reformatted later anyway.

**Comment by squidcc** [comment]
So in the meantime how can I avoid my PRs being nitpicked to death due to not abiding by undocumented rules?

Does the original source code use spaces after/before opening/closing brackets?

It doesn't look like it consistently used brackets when the body of a block was only one statement: https://github.com/nomdenom/devil-beta/blob/f32eb0ed7ec9ca33077de32d24c4548b4feb99ac/Source/control.cpp#L858

**Comment by AJenbo** [comment]
Nice find line 810 also seam to both indicate that they didn't use brackets for single line statments, and confirm that the brackets where on the same line as the if. Also 818 gives us a strong indication that both braces where on the same line as else. I'll add this to the formatting issue.

The most important things for getting your code merged is that the changes either bring the resulting ASM in line with the original exe, or doesn't change it (like adding enums etc). In some of my early PRs I was also struggling to get this righ: https://github.com/diasurgical/devil-nightly/pull/1
So to reiterate what @seritools wrote in the first comment, code style would be nice to have, but the important part is the resulting ASM.

In regards to code style for what we haven't concluded on yet we try to either stick to what was there before clean up or debate it on Discord before hand.

As you have noted some personal style might slip by, this should eventually be brought in line, if you want to help nail down the code style you should join us on the chat.

**Comment by seritools** [comment]
Will look into the changed commits, thanks :)

The style note from my initial reply wasn't meant to be understood that harshly, basically just that the missing spacing in stuff like `(GetAutomapType(x, y-1, FALSE)&0x4000)` makes it really dense and hard to read.

About the braces:
It seems that they used oneliners in a lot of cases. Look at https://github.com/nomdenom/devil-beta/blob/f32eb0ed7ec9ca33077de32d24c4548b4feb99ac/Source/control.cpp#L871 for example. That had to be

```cpp
  pSBkIconCels = LoadFileInMem("Data\\SpellI2.CEL", 0, 1076, "C:\\Diablo\\Direct\\CONTROL.CPP");
  sbooktab = 0;
  sbookflag = 0;
  if ( plr[myplr]._pClass == PC_WARRIOR) SpellPages[0][0] = 26;
  else if ( plr[myplr]._pClass == PC_ROGUE) SpellPages[0][0] = 28;
  else if ( plr[myplr]._pClass == PC_SORCERER) SpellPages[0][0] = 27;

  pQLogCel = LoadFileInMem("Data\\Quest.CEL", 0, 1083, "C:\\Diablo\\Direct\\CONTROL.CPP");
```
(could also be braced like `if ( plr[myplr]._pClass == PC_WARRIOR) { SpellPages[0][0] = 26; }` too, but for oneliners I'd prefer unbraced as well)

This one doesn't even leave enough space for putting the assignments on their own lines, let alone for lines with just empty braces. In other cases it could very well be that there are no braces for some statements, but I didn't find a single case where that would be necessary to fit in the line count supplied.
I'm guessing they also used newlines somewhere, so L858 you posted could be

```cpp
  pChrButtons = LoadFileInMem("Data\\CharBut.CEL", 0, 1061, "C:\\Diablo\\Direct\\CONTROL.CPP");
  for ( k = 0; k < 4; ++k ) chrbtn[k] = 0;
  chrbtnactive = 0;

  pDurIcons = LoadFileInMem("Items\\DurIcons.CEL", 0, 1065, "C:\\Diablo\\Direct\\CONTROL.CPP");
```
just as well. If you find cases where that is very unlikely/wrong please let me know! :)

**Comment by seritools** [comment]
Assembly looks good now :)

Stuff I changed:

- Renamed the parameters back to `x` and `y` to match the [PSX symbols](https://github.com/sanctuary/psx/tree/master/easy-as-pie), same thing about adding `xx` and `yy` and ordering it in PSX symbol order
- Switched the shots to unsigned, again because of the PSX symbols
- Added spacing between the operators to be a bit more readable
- Indented the switch cases to match the indentation of the rest of the project

**Comment by squidcc** [comment]
Are you sure the assembly output is still good with xx and yy being signed? The reason I had to put the x and y parameters in unsigned arguments was because otherwise it wouldn't generate the same array loads.

**Comment by AJenbo** [comment]
I can confirm that it is still bin exact, afaik the compiler is often able to know that some thing is not negative if left shift is used, maybe that's why this works.

**Comment by AJenbo** [comment]
132 lines of ASM fixed, nice!

**Comment by squidcc** [comment]
I'm a bit iffy about having variables declared mid-function like that; it's valid in C++ but I believe this was originally C code, and Visual C++ always used to complain about it.

**Comment by seritools** [comment]
I knew you'd mention that :P

It's the same with declarations in for loops (`for (int i = 0;;)`). Was also only officially added in C99, but VC allows it because VC. We can change it back should that interfere with something.

**Comment by squidcc** [comment]
VC always allowed declarations in for loops until they decided to mess everyone up and remove it somewhere around VC8 or 9, then backtracked and added the /Zc:forScope option for compatibility. But they definitely didn't allow variables to be declared in plain C after the first non-declaration statement in a control block.

**Pull request merged**
