### PR TITLE
Cleaned up `CreatePlayer`.

### PR DESCRIPTION
**Pull request by seritools**
This is now as close as it gets without switching to enum types/parameters everywhere, so the compiler can optimize all accesses/checks accordingly. This is especially noticeable in the way the code for the switch is generated (line 775). In the original binary you can see it does weird stuff if `c` is not one of the classes' enum value (probably due to optimization since the switch *should* be exhaustive).

I've tried switching the type of `c` to `_ui_classes`, also removing the `UI_NUM_CLASSES` value to see if that'd be enough to let it generate the optimized code, but nope, seems like we need to change it all at once. Currently, `_pClass` is a `char`, but an enum value would fit there as well, size-wise (alignment).

That's also why I'm guessing there had to be another enum for player classes, without the `UI_NUM_CLASSES` value...

### CODE REVIEW

**Comment by seritools** [comment]
Force pushed again removing the jump label indentation changes. (Fixed VS code formatting settings while at it ;))

**Comment by seritools** [comment]
Note to self (from @galaxyhaxz): revert the `#define` change and instead use a `(DWORD)` cast on `pnum`.

**Comment by galaxyhaxz** [comment]
> That's also why I'm guessing there had to be another enum for player classes, without the UI_NUM_CLASSES value...

Correct, `UI_NUM_CLASSES` is only used by DiabloUI.dll. The actual game uses a different enum as per assert strings in the debug release. We only have this:
`NUM_CLASSES` which is 3

**Comment by seritools** [comment]
So correct would be to create another enum with only the actual types and just `#define` a `NUM_CLASSES`?

**Comment by galaxyhaxz** [comment]
Main game (all guessed except `NUM_CLASSES`
```
enum _plr_classes
{
	PC_WARRIOR = 0x0,
	PC_ROGUE = 0x1,
	PC_SORCERER = 0x2,
	NUM_CLASSES = 0x3,
};
```
UI, correct and taken from psx
```
enum _ui_classes
{
	UI_WARRIOR = 0x0,
	UI_ROGUE = 0x1,
	UI_SORCERER = 0x2,
	UI_NUM_CLASSES = 0x3,
};
```

**Comment by seritools** [comment]
Now there are only scheduling/instruction ordering differences left, which cause some instructions to be reordered.

Tried VC6SP0-SP5 and all the different "Optimize for CPU" settings, to no avail. :(

**Pull request merged**
