### PR TITLE
Cleanup DRLG_Init_Globals

### PR DESCRIPTION
**Pull request by mewmew**
Almost binary identical. Only one register that gets assigned to `eax` instead of `al`. Any ideas on how to get the original?
2018-09-16-204420_958x1054_scrot

### CODE REVIEW

**Comment by AJenbo** [comment]
What if you change lightflag to be a char?

**Comment by seritools** [comment]
@AJenbo pretty sure those are even `BOOL`s, so not char :)

**Comment by AJenbo** [comment]
BOOL is 32bit so in that case I have no idea what so try to get it to do 8 bit operations :)

**Comment by mewmew** [comment]
> What if you change light4flag (or maybe lightflag) to be a char?

I tried with `char`, then 
```
cmp [0x525728], ebx
```
became
```
cmp [0x523D5C], bl
```
It should be `ebx`.

> @AJenbo pretty sure those are even BOOLs, so not char :)

Tried with bool, and that keeps `ebx`, as in the original, but does not affect `eax`.

Perhaps if we update the signature of `memset` to take a char as the second argument?

**Comment by mewmew** [comment]
From it's usage `light4flag` definitely looks like a BOOL, so I'll update that regardless

```
u@x1 ~/D/d/d/Source> ack light4flag
Binary file matches: engine.obj
Binary file matches: gendung.obj
engine.cpp:				v14 = -(light4flag != 0);
engine.cpp:// 525728: using guessed type int light4flag;
engine.cpp:				v13 = -(light4flag != 0);
engine.cpp:// 525728: using guessed type int light4flag;
engine.cpp:					v15 = -(light4flag != 0);
engine.cpp:// 525728: using guessed type int light4flag;
engine.cpp:					v15 = -(light4flag != 0);
engine.cpp:// 525728: using guessed type int light4flag;
Binary file matches: lighting.obj
Binary file matches: control.obj
control.cpp:	v0 = -(light4flag != 0);
control.cpp:// 525728: using guessed type int light4flag;
diablo.cpp:char light4flag; // weak
diablo.h:extern char light4flag; // weak
lighting.cpp:	v1 = light4flag != 0 ? 3 : 15;
lighting.cpp:	v50 = light4flag != 0 ? 3 : 15;
lighting.cpp:		v49 = light4flag != 0 ? 3 : 15;
lighting.cpp:			if ( light4flag )
lighting.cpp:// 525728: using guessed type int light4flag;
lighting.cpp:	lightmax = light4flag == 0 ? 15 : 3;
lighting.cpp:// 525728: using guessed type int light4flag;
lighting.cpp:		if ( (light4flag != 0 ? 4 : 16) > 0 )
lighting.cpp:			v1 = light4flag != 0 ? 4 : 16;
lighting.cpp:// 525728: using guessed type int light4flag;
gendung.cpp:	if ( light4flag )
gendung.cpp:	v23 = -(light4flag != 0);
gendung.cpp:// 525728: using guessed type int light4flag;
Binary file matches: drlg_l1.obj
Binary file matches: diablo.obj
drlg_l1.cpp:		c = light4flag != 0 ? 3 : 15;
drlg_l1.cpp:// 525728: using guessed type int light4flag;
```

**Comment by mewmew** [comment]
> BOOL is 32bit so in that case I have no idea what so try to get it to do 8 bit operations :)

The `eax` register is not related to `light4flag` per say, but rather the second argument to `memset`, which may be a char.

**Comment by seritools** [comment]
`memset` is stdlib, you can't change the sig :P

But those are all char arrays. Try replacing the `memset`s with for loops, which the compiler turns back into `memset`.

lightflag and light4flag both look like `BOOL`s.

**Comment by mewmew** [comment]
Ignore my last comment, I mixed up `light4flag` and `lightflag`. Thought they were one and the same.

**Comment by mewmew** [comment]
The code is binary exact now. I had the wrong version of VC6 installed (I had VC6 + SP3). Now, on VC6 + SP5 + PP, the code is binary exact.

**Comment by mewmew** [comment]
Thanks for helping with the troubleshooting!

**Comment by mewmew** [comment]
Do you have a preference regarding the use of ternary statements?
* Always use if-else
* Use ternary for simple `x = (cond) ? 10 : 20;`

**Comment by AJenbo** [comment]
I'm pretty sure that we have concluded that ternary where some times used, though not very frequently. Personally I prefer not having () around the condition, partially because if it need it isn't not good to have as a ternary.

**Comment by mewmew** [comment]
> 

Good to know. Regarding `c = light4flag != 0 ? 3 : 15;`, should we use ternary for this?

**Comment by galaxyhaxz** [comment]
It's difficult to say based on the line numbers. According to the PSX, the function is 36 lines and long and has the local variables `x/y`. So the memsets should be broken down into two `for` loops.

**Comment by seritools** [comment]
> But those are all char arrays. Try replacing the memsets with for loops, which the compiler turns back into memset.

still waiting for that :P

**Comment by galaxyhaxz** [comment]
From the PR demo:
```
void __cdecl DRLG_Init_Globals()
{
	for(int y = 0; y < MAXDUNY; y++)
	{
		for(int x = 0; x < MAXDUNX; x++)
		{
			if ( lightflag )
			{
				dTransVal[x][y] = 0;
			}
			else if ( light4flag )
			{
				dTransVal[x][y] = 3;
			}
			else
			{
				dTransVal[x][y] = 15;
			}
			dFlags[x][y] = 0;
			dPlayer[x][y] = 0;
			dMonster[x][y] = 0;
			dDead[x][y] = 0;
			dObject[x][y] = 0;
			dItem[x][y] = 0;
			dMissile[x][y] = 0;
			dArch[x][y] = 0;
		}
	}
}
```

**Comment by mewmew** [comment]
I tried with

```c
void __cdecl DRLG_Init_Globals()
{
	for (int y = 0; y < MAXDUNY; y++)
	{
		for (int x = 0; x < MAXDUNX; x++)
		{
			dFlags[x][y] = 0;
			dPlayer[x][y] = 0;
			dMonster[x][y] = 0;
			dDead[x][y] = 0;
			dObject[x][y] = 0;
			dItem[x][y] = 0;
			dMissile[x][y] = 0;
			dArch[x][y] = 0;
			if ( lightflag )
			{
				dTransVal[x][y] = 0;
			}
			else if ( lightflag )
			{
				dTransVal[x][y] = 3;
			}
			else
			{
				dTransVal[x][y] = 15;
			}
		}
	}
}
```

But it is now far from binary exact:

2018-09-16-232544_1278x1414_scrot

How did you manage to get the compiler to turn the for loops into memsets? Doesn't look like that happened for the code above.

**Comment by galaxyhaxz** [comment]
So now it's too optimized, interesting. That's the raw code as it comes from the PR demo, I didn't test it yet. But seeing how it's far from perfect, it's possible they changed the for loop to a memset later on.

**Comment by seritools** [comment]
>How did you manage to get the compiler to turn the for loops into memsets? Doesn't look like that happened for the code above.

Was more like a suggestion ;) There are many cases where that worked. You checked `lightflag` twice instead of `lightflag` and `light4flag` once each, though.

**Comment by seritools** [comment]
Just checked, yup, the compiler doesn't want to generate a memset call on its own here. Starting from the beta every version seems to have memsets there as well, so LGTM :)

**Pull request merged**
